      throw new FaultException<int>(4);